image: node:16.15.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - pnpm-lock.yaml
      prefix: npm
    paths:
      - node_modules/
  script:
    - pnpm install
    - pnpm build
    - pnpm docs:build
    - cp -a docs/.vitepress/dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
