/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/echart/src/BarChart.vue')['default']
    BaseChart: typeof import('./src/components/echart/src/BaseChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    ItemCascader: typeof import('@/basis-components/form-items/itemCascader.vue')['default']
    ItemCheckbox: typeof import('@/basis-components/form-items/itemCheckbox.vue')['default']
    ItemDate: typeof import('@/basis-components/form-items/itemDate.vue')['default']
    ItemDateTime: typeof import('@/basis-components/form-items/itemDateTime.vue')['default']
    ItemInput: typeof import('@/basis-components/form-items/itemInput.vue')['default']
    ItemInputNumber: typeof import('@/basis-components/form-items/itemInputNumber.vue')['default']
    ItemRadio: typeof import('@/basis-components/form-items/itemRadio.vue')['default']
    ItemRate: typeof import('@/basis-components/form-items/itemRate.vue')['default']
    ItemSelect: typeof import('@/basis-components/form-items/itemSelect.vue')['default']
    ItemSwitch: typeof import('@/basis-components/form-items/itemSwitch.vue')['default']
    ItemTimePicker: typeof import('@/basis-components/form-items/itemTimePicker.vue')['default']
    ItemTimeSelect: typeof import('@/basis-components/form-items/itemTimeSelect.vue')['default']
    LineChart: typeof import('./src/components/echart/src/LineChart.vue')['default']
    NavTabs: typeof import('./src/components/layout-router/src/NavTabs.vue')['default']
    NodeMenu: typeof import('./src/components/layout-menu/src/NodeMenu.vue')['default']
    PieChart: typeof import('./src/components/echart/src/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/dialog/src/index.vue')['default']
    TableColumn: typeof import('./src/components/table/src/components/TableColumn.vue')['default']
    UploadInfo: typeof import('./src/components/uploader/src/components/UploadInfo.vue')['default']
    UploadList: typeof import('./src/components/uploader/src/components/UploadList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
